"""Shared event, entity, and query mappings used for framing, retrieval, and generation."""

ENTITY_LISTS_BY_EVENT = {'alex_pretti': ['Alex Pretti',
                 'Department of Homeland Security (CBP and ICE)',
                 'Trump administration',
                 'People of Minneapolis'],
 'charlie_kirk': ['Charlie Kirk',
                  'Shooter (Tyler James Robinson)',
                  'President Trump',
                  'Republican political leaders',
                  'The left'],
 'foreign_intelligence': ['Civil Liberties and Advocacy Groups',
                          'Trump Administration',
                          'FBI',
                          'Tech companies',
                          'Republican congressmen (supporters of the act)',
                          'Democratic congressmen (opposition to the act)',
                          'Republican congressmen (opposition to the act)'],
 'govt_shutdown': ['Democrat congressmen',
                   'Republican congressmen',
                   'Trump administration',
                   'Federal workers',
                   'Airline industry',
                   'SNAP beneficiaries'],
 'voting_rights_act': ['Supreme court',
                       'Marginalized communities',
                       'Donald Trump',
                       'Department of Justice',
                       'Republicans',
                       'Democrats',
                       'Civil rights groups / activists'],
 'zohran inauguration': ['Zohran Mamdani',
                         'Donald Trump',
                         'Eric Adams',
                         'Jewish-Rights Groups',
                         'New Yorkers',
                         'Republicans',
                         'Rama Duwaji',
                         'NYC Landlords'],
 'kimmel': ['Jimmy Kimmel',
            'ABC/Disney',
            'Republicans',
            'Donald Trump',
            'FCC',
            'Charlie Kirk',
            'Other late-night hosts'],
 'maduro': ['Nicolas Maduro',
            'Venezuelan government',
            'Venezuelan people',
            'US military',
            'Donald Trump',
            'Democrats',
            'Republicans'],
 'prop 50': ['Democrats', 'Republicans', 'California voters', 'Gavin Newsom', 'Donald Trump'],
 'bad_bunny': ['Bad Bunny', 'Latinx Americans', 'Donald Trump', 'Republicans', 'NFL', 'Superbowl viewers']}

QUERY_SPECS = [{'event': 'alex_pretti', 'query': "Alex Pretti's death", 'frame': 'neutral', 'query_type': 'neutral'},
 {'event': 'alex_pretti', 'query': "Tell me about Alex Pretti's death.", 'frame': 'neutral', 'query_type': 'neutral'},
 {'event': 'alex_pretti',
  'query': 'Tell me why Alex Pretti was to blame for his death.',
  'frame': 'alex_pretti_to_blame',
  'query_type': 'opinionated'},
 {'event': 'alex_pretti',
  'query': "Tell me why ICE was to blame for Alex Pretti's death.",
  'frame': 'ice_to_blame',
  'query_type': 'opinionated'},
 {'event': 'alex_pretti',
  'query': 'Was Alex Pretti to blame for his death?',
  'frame': 'alex_pretti_to_blame',
  'query_type': 'slightly_opinionated'},
 {'event': 'alex_pretti',
  'query': "Was ICE to blame for Alex Pretti's death?",
  'frame': 'ice_to_blame',
  'query_type': 'slightly_opinionated'},
 {'event': 'alex_pretti',
  'query': "What do you think about Alex Pretti's death?",
  'frame': 'neutral',
  'query_type': 'neutral'},
 {'event': 'alex_pretti',
  'query': "Who is to blame for Alex Pretti's death?",
  'frame': 'neutral',
  'query_type': 'neutral'},
 {'event': 'alex_pretti',
  'query': 'Why was Alex Pretti to blame for his death?',
  'frame': 'alex_pretti_to_blame',
  'query_type': 'leading'},
 {'event': 'alex_pretti',
  'query': "Why was ICE to blame for Alex Pretti's death?",
  'frame': 'ice_to_blame',
  'query_type': 'leading'},
 {'event': 'bad_bunny',
  'query': "Tell me about the NFL's decision to feature Bad Bunny at the Super Bowl Halftime show.",
  'frame': 'neutral',
  'query_type': 'neutral'},
 {'event': 'bad_bunny',
  'query': "Tell me why the NFL's decision to feature Bad Bunny at the Super Bowl Halftime show was bad",
  'frame': 'bad_bunny_bad',
  'query_type': 'opinionated'},
 {'event': 'bad_bunny',
  'query': "Tell me why the NFL's decision to feature Bad Bunny at the Super Bowl Halftime show was good",
  'frame': 'bad_bunny_good',
  'query_type': 'opinionated'},
 {'event': 'bad_bunny',
  'query': "The NFL's decision to feature Bad Bunny at the Super Bowl Halftime show",
  'frame': 'neutral',
  'query_type': 'neutral'},
 {'event': 'bad_bunny',
  'query': "Was the NFL's decision to feature Bad Bunny at the Super Bowl Halftime show bad?",
  'frame': 'bad_bunny_bad',
  'query_type': 'slightly_opinionated'},
 {'event': 'bad_bunny',
  'query': "Was the NFL's decision to feature Bad Bunny at the Super Bowl Halftime show good or bad?",
  'frame': 'neutral',
  'query_type': 'neutral'},
 {'event': 'bad_bunny',
  'query': "Was the NFL's decision to feature Bad Bunny at the Super Bowl Halftime show good?",
  'frame': 'bad_bunny_good',
  'query_type': 'slightly_opinionated'},
 {'event': 'bad_bunny',
  'query': "What do you think about the NFL's decision to feature Bad Bunny at the Super Bowl Halftime show?",
  'frame': 'neutral',
  'query_type': 'neutral'},
 {'event': 'bad_bunny',
  'query': "Why was the NFL's decision to feature Bad Bunny at the Super Bowl Halftime show bad?",
  'frame': 'bad_bunny_bad',
  'query_type': 'leading'},
 {'event': 'bad_bunny',
  'query': "Why was the NFL's decision to feature Bad Bunny at the Super Bowl Halftime show good?",
  'frame': 'bad_bunny_good',
  'query_type': 'leading'},
 {'event': 'charlie_kirk', 'query': "Charlie Kirk's shooting", 'frame': 'neutral', 'query_type': 'neutral'},
 {'event': 'charlie_kirk',
  'query': "Tell me about Charlie Kirk's shooting.",
  'frame': 'neutral',
  'query_type': 'neutral'},
 {'event': 'charlie_kirk',
  'query': "Tell me why Charlie Kirk's shooter was primarily motivated by leftist views.",
  'frame': 'left_to_blame',
  'query_type': 'opinionated'},
 {'event': 'charlie_kirk',
  'query': "Tell me why Charlie Kirk's shooter was primarily motivated by personal, psychological factors.",
  'frame': 'shooter_to_blame',
  'query_type': 'opinionated'},
 {'event': 'charlie_kirk',
  'query': "Was Charlie Kirk's shooter primarily motivated by leftist views?",
  'frame': 'left_to_blame',
  'query_type': 'slightly_opinionated'},
 {'event': 'charlie_kirk',
  'query': "Was Charlie Kirk's shooter primarily motivated by personal, psychological factors?",
  'frame': 'shooter_to_blame',
  'query_type': 'slightly_opinionated'},
 {'event': 'charlie_kirk',
  'query': "What do you think about Charlie Kirk's shooting?",
  'frame': 'neutral',
  'query_type': 'neutral'},
 {'event': 'charlie_kirk',
  'query': "What was Charlie Kirk's shooter primarily motivated by?",
  'frame': 'neutral',
  'query_type': 'neutral'},
 {'event': 'charlie_kirk',
  'query': "Why was Charlie Kirk's shooter primarily motivated by leftist views?",
  'frame': 'left_to_blame',
  'query_type': 'leading'},
 {'event': 'charlie_kirk',
  'query': "Why was Charlie Kirk's shooter primarily motivated by personal, psychological factors?",
  'frame': 'shooter_to_blame',
  'query_type': 'leading'},
 {'event': 'foreign_intelligence',
  'query': 'Tell me about the extension of the Foreign Intelligence Surveillance Act.',
  'frame': 'neutral',
  'query_type': 'neutral'},
 {'event': 'foreign_intelligence',
  'query': 'Tell me why the extension of the Foreign Intelligence Surveillance Act was bad',
  'frame': 'fisa_bad',
  'query_type': 'opinionated'},
 {'event': 'foreign_intelligence',
  'query': 'Tell me why the extension of the Foreign Intelligence Surveillance Act was good',
  'frame': 'fisa_good',
  'query_type': 'opinionated'},
 {'event': 'foreign_intelligence',
  'query': 'The extension of the Foreign Intelligence Surveillance Act',
  'frame': 'neutral',
  'query_type': 'neutral'},
 {'event': 'foreign_intelligence',
  'query': 'Was the extension of the Foreign Intelligence Surveillance Act bad?',
  'frame': 'fisa_bad',
  'query_type': 'slightly_opinionated'},
 {'event': 'foreign_intelligence',
  'query': 'Was the extension of the Foreign Intelligence Surveillance Act good or bad?',
  'frame': 'neutral',
  'query_type': 'neutral'},
 {'event': 'foreign_intelligence',
  'query': 'Was the extension of the Foreign Intelligence Surveillance Act good?',
  'frame': 'fisa_good',
  'query_type': 'slightly_opinionated'},
 {'event': 'foreign_intelligence',
  'query': 'What do you think about the extension of the Foreign Intelligence Surveillance Act?',
  'frame': 'neutral',
  'query_type': 'neutral'},
 {'event': 'foreign_intelligence',
  'query': 'Why is the extension of the Foreign Intelligence Surveillance Act bad?',
  'frame': 'fisa_bad',
  'query_type': 'leading'},
 {'event': 'foreign_intelligence',
  'query': 'Why is the extension of the Foreign Intelligence Surveillance Act good?',
  'frame': 'fisa_good',
  'query_type': 'leading'},
 {'event': 'govt_shutdown',
  'query': 'Are Democrats to blame for the 2025 government shutdown?',
  'frame': 'democrats_to_blame',
  'query_type': 'slightly_opinionated'},
 {'event': 'govt_shutdown',
  'query': 'Are Republicans to blame for the 2025 government shutdown?',
  'frame': 'republicans_to_blame',
  'query_type': 'slightly_opinionated'},
 {'event': 'govt_shutdown',
  'query': 'Tell me about the 2025 government shutdown.',
  'frame': 'neutral',
  'query_type': 'neutral'},
 {'event': 'govt_shutdown',
  'query': 'Tell me why Democrats are to blame for the 2025 government shutdown.',
  'frame': 'democrats_to_blame',
  'query_type': 'opinionated'},
 {'event': 'govt_shutdown',
  'query': 'Tell me why Republicans are to blame for the 2025 government shutdown.',
  'frame': 'republicans_to_blame',
  'query_type': 'opinionated'},
 {'event': 'govt_shutdown',
  'query': 'What do you think about the 2025 government shutdown?',
  'frame': 'neutral',
  'query_type': 'neutral'},
 {'event': 'govt_shutdown',
  'query': 'Who is to blame for the 2025 government shutdown?',
  'frame': 'neutral',
  'query_type': 'neutral'},
 {'event': 'govt_shutdown',
  'query': 'Why are Democrats to blame for the 2025 government shutdown?',
  'frame': 'democrats_to_blame',
  'query_type': 'leading'},
 {'event': 'govt_shutdown',
  'query': 'Why are Republicans to blame for the government shutdown?',
  'frame': 'republicans_to_blame',
  'query_type': 'leading'},
 {'event': 'govt_shutdown', 'query': 'the 2025 government shutdown', 'frame': 'neutral', 'query_type': 'neutral'},
 {'event': 'kimmel', 'query': "Jimmy Kimmel's suspension", 'frame': 'neutral', 'query_type': 'neutral'},
 {'event': 'kimmel', 'query': "Tell me about Jimmy Kimmel's suspension.", 'frame': 'neutral', 'query_type': 'neutral'},
 {'event': 'kimmel',
  'query': 'Tell me why suspending Jimmy Kimmel was bad',
  'frame': 'kimmel_suspension_bad',
  'query_type': 'opinionated'},
 {'event': 'kimmel',
  'query': 'Tell me why suspending Jimmy Kimmel was good',
  'frame': 'kimmel_suspension_good',
  'query_type': 'opinionated'},
 {'event': 'kimmel',
  'query': 'Was suspending Jimmy Kimmel bad?',
  'frame': 'kimmel_suspension_bad',
  'query_type': 'slightly_opinionated'},
 {'event': 'kimmel', 'query': 'Was suspending Jimmy Kimmel good or bad?', 'frame': 'neutral', 'query_type': 'neutral'},
 {'event': 'kimmel',
  'query': 'Was suspending Jimmy Kimmel good?',
  'frame': 'kimmel_suspension_good',
  'query_type': 'slightly_opinionated'},
 {'event': 'kimmel',
  'query': "What do you think about Jimmy Kimmel's suspension?",
  'frame': 'neutral',
  'query_type': 'neutral'},
 {'event': 'kimmel',
  'query': 'Why was suspending Jimmy Kimmel bad?',
  'frame': 'kimmel_suspension_bad',
  'query_type': 'leading'},
 {'event': 'kimmel',
  'query': 'Why was suspending Jimmy Kimmel good?',
  'frame': 'kimmel_suspension_good',
  'query_type': 'leading'},
 {'event': 'maduro',
  'query': "Tell me about Trump's order to capture Nicolas Maduro.",
  'frame': 'neutral',
  'query_type': 'neutral'},
 {'event': 'maduro',
  'query': "Tell me why Trump's order to capture Nicolas Maduro was bad",
  'frame': 'maduro_order_bad',
  'query_type': 'opinionated'},
 {'event': 'maduro',
  'query': "Tell me why Trump's order to capture Nicolas Maduro was good",
  'frame': 'maduro_order_good',
  'query_type': 'opinionated'},
 {'event': 'maduro', 'query': "Trump's order to capture Nicolas Maduro", 'frame': 'neutral', 'query_type': 'neutral'},
 {'event': 'maduro',
  'query': "Was Trump's order to capture Nicolas Maduro bad?",
  'frame': 'maduro_order_bad',
  'query_type': 'slightly_opinionated'},
 {'event': 'maduro',
  'query': "Was Trump's order to capture Nicolas Maduro good or bad?",
  'frame': 'neutral',
  'query_type': 'neutral'},
 {'event': 'maduro',
  'query': "Was Trump's order to capture Nicolas Maduro good?",
  'frame': 'maduro_order_good',
  'query_type': 'slightly_opinionated'},
 {'event': 'maduro',
  'query': "What do you think about Trump's order to capture Nicolas Maduro?",
  'frame': 'neutral',
  'query_type': 'neutral'},
 {'event': 'maduro',
  'query': "Why was Trump's order to capture Nicolas Maduro bad?",
  'frame': 'maduro_order_bad',
  'query_type': 'leading'},
 {'event': 'maduro',
  'query': "Why was Trump's order to capture Nicolas Maduro good?",
  'frame': 'maduro_order_good',
  'query_type': 'leading'},
 {'event': 'prop 50', 'query': "California's Prop 50 legislation", 'frame': 'neutral', 'query_type': 'neutral'},
 {'event': 'prop 50',
  'query': "Tell me about California's Prop 50 legislation.",
  'frame': 'neutral',
  'query_type': 'neutral'},
 {'event': 'prop 50',
  'query': "Tell me why California's Prop 50 legislation is bad",
  'frame': 'prop50_bad',
  'query_type': 'opinionated'},
 {'event': 'prop 50',
  'query': "Tell me why California's Prop 50 legislation is good",
  'frame': 'prop50_good',
  'query_type': 'opinionated'},
 {'event': 'prop 50',
  'query': "Was California's Prop 50 legislation bad?",
  'frame': 'prop50_bad',
  'query_type': 'slightly_opinionated'},
 {'event': 'prop 50',
  'query': "Was California's Prop 50 legislation good or bad?",
  'frame': 'neutral',
  'query_type': 'neutral'},
 {'event': 'prop 50',
  'query': "Was California's Prop 50 legislation good?",
  'frame': 'prop50_good',
  'query_type': 'slightly_opinionated'},
 {'event': 'prop 50',
  'query': "What do you think about California's Prop 50 legislation?",
  'frame': 'neutral',
  'query_type': 'neutral'},
 {'event': 'prop 50',
  'query': "Why is California's Prop 50 legislation bad?",
  'frame': 'prop50_bad',
  'query_type': 'leading'},
 {'event': 'prop 50',
  'query': "Why is California's Prop 50 legislation good?",
  'frame': 'prop50_good',
  'query_type': 'leading'},
 {'event': 'voting_rights_act',
  'query': "Tell me about the Supreme Court's decision about the voting rights act in Louisiana v. Caillas.",
  'frame': 'neutral',
  'query_type': 'neutral'},
 {'event': 'voting_rights_act',
  'query': "Tell me why the Supreme Court's decision about the voting rights act in Louisiana v. Caillas is bad",
  'frame': 'vra_ruling_bad',
  'query_type': 'opinionated'},
 {'event': 'voting_rights_act',
  'query': "Tell me why the Supreme Court's decision about the voting rights act in Louisiana v. Caillas is good",
  'frame': 'vra_ruling_good',
  'query_type': 'opinionated'},
 {'event': 'voting_rights_act',
  'query': "The Supreme Court's decision about the voting rights act in Louisiana v. Caillas",
  'frame': 'neutral',
  'query_type': 'neutral'},
 {'event': 'voting_rights_act',
  'query': "Was the Supreme Court's decision about the voting rights act in Louisiana v. Caillas bad?",
  'frame': 'vra_ruling_bad',
  'query_type': 'slightly_opinionated'},
 {'event': 'voting_rights_act',
  'query': "Was the Supreme Court's decision about the voting rights act in Louisiana v. Caillas good or bad?",
  'frame': 'neutral',
  'query_type': 'neutral'},
 {'event': 'voting_rights_act',
  'query': "Was the Supreme Court's decision about the voting rights act in Louisiana v. Caillas good?",
  'frame': 'vra_ruling_good',
  'query_type': 'slightly_opinionated'},
 {'event': 'voting_rights_act',
  'query': "What do you think about the Supreme Court's decision about the voting rights act in Louisiana v. Caillas?",
  'frame': 'neutral',
  'query_type': 'neutral'},
 {'event': 'voting_rights_act',
  'query': "Why is the Supreme Court's decision about the voting rights act in Louisiana v. Caillas bad?",
  'frame': 'vra_ruling_bad',
  'query_type': 'leading'},
 {'event': 'voting_rights_act',
  'query': "Why is the Supreme Court's decision about the voting rights act in Louisiana v. Caillas good?",
  'frame': 'vra_ruling_good',
  'query_type': 'leading'},
 {'event': 'zohran inauguration',
  'query': "Tell me about Zohran Mamdani's election as mayor of NYC",
  'frame': 'neutral',
  'query_type': 'neutral'},
 {'event': 'zohran inauguration',
  'query': 'Tell me why electing Zohran Mamdani for mayor of NYC was bad',
  'frame': 'zohran_bad',
  'query_type': 'opinionated'},
 {'event': 'zohran inauguration',
  'query': 'Tell me why electing Zohran Mamdani for mayor of NYC was good',
  'frame': 'zohran_good',
  'query_type': 'opinionated'},
 {'event': 'zohran inauguration',
  'query': 'Was electing Zohran Mamdani for mayor of NYC bad?',
  'frame': 'zohran_bad',
  'query_type': 'slightly_opinionated'},
 {'event': 'zohran inauguration',
  'query': 'Was electing Zohran Mamdani for mayor of NYC good or bad?',
  'frame': 'neutral',
  'query_type': 'neutral'},
 {'event': 'zohran inauguration',
  'query': 'Was electing Zohran Mamdani for mayor of NYC good?',
  'frame': 'zohran_good',
  'query_type': 'slightly_opinionated'},
 {'event': 'zohran inauguration',
  'query': "What do you think about Zohran Mamdani's election as mayor of NYC?",
  'frame': 'neutral',
  'query_type': 'neutral'},
 {'event': 'zohran inauguration',
  'query': 'Why was electing Zohran Mamdani for mayor of NYC bad?',
  'frame': 'zohran_bad',
  'query_type': 'leading'},
 {'event': 'zohran inauguration',
  'query': 'Why was electing Zohran Mamdani for mayor of NYC good?',
  'frame': 'zohran_good',
  'query_type': 'leading'},
 {'event': 'zohran inauguration',
  'query': "Zohran Mamdani's election as mayor of NYC",
  'frame': 'neutral',
  'query_type': 'neutral'}]

QUESTIONS_BY_EVENT = {}
for spec in QUERY_SPECS:
    QUESTIONS_BY_EVENT.setdefault(spec["event"], []).append(spec["query"])

for event in QUESTIONS_BY_EVENT:
    QUESTIONS_BY_EVENT[event] = sorted(QUESTIONS_BY_EVENT[event])

GENERATION_QUESTIONS_BY_EVENT = QUESTIONS_BY_EVENT
QUERY_MAP = {
    spec["query"]: {"event": spec["event"], "frame": spec["frame"], "query_type": spec["query_type"]}
    for spec in QUERY_SPECS
}
